### ISSUE TITLE
Swift 2.0?

### ISSUE THREAD

**Issue by stuffmc** [giacgbj/UIImage-Swift-Extensions#3]
Do you have a branch for this code in Swift 2.0? ;-) Thanks!

**Comment by giacgbj** [comment]
I've just created a branch (swift2.0) where I've migrated the previous code. Everything compiles, but I can't test the code because I cannot migrate (yet) to Swift 2.0 the application in which I use these methods.
Please, let me know if it works.

**Comment by stuffmc** [comment]
Great. Can't look at it _right now_ either but might do soon. Also, is it okay for you if I use it in a video tutorial I'm working on?

**Comment by serg94** [comment]
+

**Comment by lluisgerard** [comment]
It works, I also forked the swift-2.0 branch because I had some issues with some PNG files with transparent channels but I'm forcing images to 8bit so that's why I'm not doing a pull request yet.
If you want to take a look: https://github.com/lluisgerard/UIImageSwiftExtensions

But anyway, this issue can be closed because the swift-2.0 works fine, maybe even merged to the master one at this point :+1:

**Comment by lammertw** [comment]
It's been a while since Swift 2 is out so it would be great to have it on master and have a new release with it.

**Comment by giacgbj** [comment]
swift2.0 branch merged into the master and release 2.0 created.
New pod deployed with the version 2.0.
